name: base_env
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - python=3.9
  - imbalanced-learn
  - scikit-learn
  - scipy
  - pip
  - pip:
    - aif360aif360[OptimPreproc, LFR, AdversarialDebiasing, DisparateImpactRemover, LIME, ART, Reductions]
