name: Release to Zenodo on Push to Main
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Zenodo CLI
        run: |
          pip install zenodo-cli
        env:
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_ACCESS_TOKEN }}

      - name: Publish to Zenodo
        run: |
          # Replace 'your_version_number' with the actual version number of your application.
          zenodo-cli create --title "MANILA" --publish --upload ./*
        env:
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_ACCESS_TOKEN }}
